version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"  # LocalStack Gateway
      - "4572:4572"  # S3
      - "4597:4597"  # EKS
      - "4598:4598"  # EC2
    environment:
      - SERVICES=s3,ec2,eks
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - LAMBDA_EXECUTOR=docker-reuse
    volumes:
      - "./localstack:/tmp/localstack"
